### ISSUE TITLE
How to give access to all the inventory without putting all the group host in the servers variable

### ISSUE THREAD

**Issue by Suertzz** [ryandaniels/ansible-role-create-users#16]
Hi, 

By default, is it possible to give a user access to all the hosts in the inventory? 
For example, by putting in the 'servers' variable:

`- global`
or
`- all`

Instead of listing the host list like this :

``` - username: testuser104
   primarygroup: testgroup104primary
    ssh_key: ssh-rsa AAAB.... test103@server
   exclusive_ssh_key: no
   use_sudo: no
   user_state: present
   servers:
     - webserver
    - monitoring
    - group1
    - group2
    - group3
    - group4
```

**Comment by ryandaniels** [comment]
Yes, Ansible does this for you!
This role is using your Ansible Inventory file groups. So you can use the built-in way that Ansible handles groups in the Inventory file. By default Ansible allows use of the `all` Inventory group.
See: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#default-groups

**Comment by Talal-l** [comment]
Not sure if things have changed since this was closed, but on ansible 2.10.5 I had to add the `all` groups to `group_names` manually since it's omitted by default. 

> Though all and ungrouped are always present, they can be implicit and not appear in group listings like group_names.
from https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#default-groups

**Comment by maybe-hello-world** [comment]
@ryandaniels can you reopen this issue?
I confirm that on ansible 2.13.3 adding 'all' to user servers does not work.
As @Talal-l mentioned, it's probably because `all` isn't in `group_names` and therefore the intersection operation does not produce any output. Maybe it changed due to #19.

**Comment by sakoula** [comment]
hi! Thanks for the great module! Is there a way not to use the `servers` variable but instead do something like this and apply the create_users to host srv01 or whatever hosts is pointing to?

Thanks!

```
- name: setup users
  hosts: srv01
  vars_files:
    - ../security/users.yaml
  become: yes
  roles:
    - create_users
 ```

**Comment by ryandaniels** [comment]
I'm using Ansible 2.9.x
Could you try using an older version? v1.0.6 was before #19 intersect change.

**Comment by ryandaniels** [comment]
This has been fixed as suggested by @Talal-l, by adding "all" to group_names (as a new variable)
