### ISSUE TITLE
Cannot ssh using created users

### ISSUE THREAD

**Issue by tdoan2010** [ryandaniels/ansible-role-create-users#17]
Hi, when I create a user and assign it an `ssh` key, I expect that I can `ssh` to the server using that user account. Could you add that feature? Maybe just simply modify the `/etc/ssh/sshd_config` file?

**Comment by ryandaniels** [comment]
Yes that's what this does. See documentation: https://github.com/ryandaniels/ansible-role-create-users#user-settings (ssh_key)

**Comment by tdoan2010** [comment]
The `ssh_key` part is there just to add the key to the `authorized_key` file of the user. It doesn't mean that I can `ssh` to my server using that user. I checked your code in `tasks/main.yml` but I don't see any task which allows users to `ssh`.

For example, I create a user `test` at `my-server` with an `ssh_key`. Then, I try `ssh test@my-server` and get `Permission denied (Public key)` although I have the correct private key here.

**Comment by ryandaniels** [comment]
It sounds like you are looking for a role to configure ssh. This role only creates users.
