### ISSUE TITLE
Documentation is not clear in how to setup server variables

### ISSUE THREAD

**Issue by royvandongen** [ryandaniels/ansible-role-create-users#2]
I tried to use this Ansible Role, but ran into some issues. You might want to update the documentation about this. With errors like below, it took me a while to find the sentence "This is done on a per "group" basis (Ansible group variables), as set in the config file. The group comes from the Ansible group as set for a server in the inventory file." in the README. However it is not stated how to declare those variables, in what format or so.

At this moment running the role, will result in a message like this.
`fatal: [HOSTNAME]: FAILED! => {"msg": "The conditional check '(item.0.user_state == 'present' or item.0.user_state == 'lock') and item.1 in group_names' failed. The error was: error while evaluating conditional ((item.0.user_state == 'present' or item.0.user_state == 'lock') and item.1 in group_names): 'dict object' has no attribute 'user_state'\n\nThe error appears to have been in '/home/ansible/ansible/roles/create_users/tasks/main.yml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add users | create users, shell, home dirs\n  ^ here\n"}`

**Comment by ryandaniels** [comment]
Fixed in commit https://github.com/ryandaniels/ansible-role-create-users/commit/687b3276b5935b05796e973542c4b261a923a99b
