### ISSUE TITLE
Allow servers be cerain server instead of group

### ISSUE THREAD

**Issue by Pyton** [ryandaniels/ansible-role-create-users#20]
Sometimes there is a case to add user to only one server instead of all servers in a group.

**Comment by maybe-hello-world** [comment]
@ryandaniels can you please comment on whether this is discussable and #32 could be merged? This is a valid use case for us as well with 10 servers and bogus groups per server

**Comment by yogo1212** [comment]
@maybe-hello-world if you're only just starting to manage users using ansible, maybe invest your time into some other project.
i only worked on this code to help out someone dear to me who was already locked in. the design is very specific to a particular use case and the code looks horrible (sorry)

**Comment by ryandaniels** [comment]
Re-opening. PR #32 is almost working. Once fixed and tests pass it can be merged

**Comment by ionut-tanasa** [comment]
hi @ryandaniels any news on this one?

**Comment by ryandaniels** [comment]
Fixed in PR #37
