### ISSUE TITLE
Allow to specify url with SSH public keys for a user

### ISSUE THREAD

**Issue by maybe-hello-world** [ryandaniels/ansible-role-create-users#22]
Some websites (such as GitHub and GitLab) provide users' public SSH keys in a plain-text format via a public link.

Example: 
- https://github.com/maybe-hello-world.keys
- https://gitlab.com/maybe-hello-world.keys

Is it possible to add a parameter to provide an URL with this info instead of ssh keys themselves, so the task would download keys from the provided link? It would facilitate key management for teams with established github/gitlab organizations or other key distribution methods and remove unneeded secrets file updates if keys change.

**Comment by ryandaniels** [comment]
Yes, this is built into Ansible already. 
Set "ssh_key" from this project, to the url of your ssh key.

Check out the documentation for some examples: https://docs.ansible.com/ansible/2.9/modules/authorized_key_module.html#parameter-key
