### ISSUE TITLE
Have generate_ssh_key include the username

### ISSUE THREAD

**Issue by cubistico** [ryandaniels/ansible-role-create-users#24]
Is there any way to have generate_ssh_key include the username after the generated key (like ssh-keygen does)?

Reason for this requirement: 

I have servers that can ssh to other servers under another username, and it's very confusing not to be able see which user the generated ssh key is for.

**Comment by ryandaniels** [comment]
Yes anything can go in the "comment" field after the ssh key. See examples
in the readme

**Comment by ryandaniels** [comment]
Yes see examples in readme

**Comment by ryandaniels** [comment]
latest commit adds this feature (release 1.0.8)

**Comment by cubistico** [comment]
I tested, and it works, but I'm afraid it's not what I need, because:

With `ssh_key_comment`, I can add a comment for that user, but that is going to be the same on all servers.

However, what I need is the username _and_ the servername that this key was generated for in the comment, so I can distinguish them. With the new option, if now I generate keys for user `testuser` on 10 servers, I get 10 different keys which all have the same comment. That's not helpful.

Also, I actually don't want to specify a comment manually, because all the information I want in the comment is already available:
````
ssh-rsa AAAAB3N[...]
GLxnzvfKz5nWCT5YfK2TtTg7MWcc6FhOem1XOi+kyjQKCbE= <username>@<servername>
````
or perhaps more similar to the old style
````
ssh-rsa AAAAB3N[...]
GLxnzvfKz5nWCT5YfK2TtTg7MWcc6FhOem1XOi+kyjQKCbE= ansible-generated for <username> on <servername>
````
Apologies if I didn't express myself clear enough before!

Thanks

**Comment by ryandaniels** [comment]
This makes sense. I created a new PR if you can verify #25
