### ISSUE TITLE
The role fails on check mode when adding a new user

### ISSUE THREAD

**Issue by BapRx** [ryandaniels/ansible-role-create-users#30]
Hey @ryandaniels, thank you for this useful role, I have an issue when creating new users if they have configured SSH public keys:
```log
failed: [vm-1] (item=username: my-user, ssh_key: True, exclusive_ssh_key: True) => {"ansible_loop_var": "item", "changed": false, "item": {"exclusive_ssh_key": true, "servers": ["all"], "ssh_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFyipFv98/Zp0e2pljNVVvtm1dHdYCx0njinKOuVZL my-user@example.com.fr\n", "use_sudo": false, "use_sudo_nopass": true, "user_state": "present", "username": "my-user"}, "msg": "Either user must exist or you must provide full path to key file in check mode"}
```

Our workflow fails if the check mode wasn't successful so we really need it to complete.

I've creating the following PR to address this issue: https://github.com/ryandaniels/ansible-role-create-users/pull/29

I'm providing the default path `/home/<username>/.ssh/authorized_keys` only if the check mode is enabled, nothing when running without it.

Please tell me if you have a suggestion or any other comment about it, thank you.

**Comment by BapRx** [comment]
Can you create a new release to make it available on Galaxy? Thank you!

**Comment by ryandaniels** [comment]
Done!
