### ISSUE TITLE
Creation of groups via comma separated list does not seem to work

### ISSUE THREAD

**Issue by royvandongen** [ryandaniels/ansible-role-create-users#7]
Destination server: Ubuntu 18:04 LTS.

When trying to create group membership via this module, error messages like: 
`groupadd: '['users', 'sudo']' is not a valid group name\n` are shown.

I tried adding the comma separated list with all the groups multiple ways, but it always reverts to this error, looking to me like Ansible is not understanding the format of the comma separated input. There is no example in the documentation stating the correct input format. and i have too little experience with ansible yet, to be able to reverse engineer this.

My apologies for this.

**Comment by ryandaniels** [comment]
Thanks for reporting this bug.
It's fixed.
